export const ACCOUNTS_CONTRACT_ADDRESS = '0xe19e7379699E0150fF6F1A2f462b30ec332D2940';

export const ACCOUNTS_CONTRACT_ABI = [
  {
    inputs: [
      { internalType: 'address', name: '_router', type: 'address' },
      { internalType: 'address', name: '_link', type: 'address' },
      { internalType: 'address', name: '_accountImplementation', type: 'address' },
      { internalType: 'address', name: '_manager', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [{ internalType: 'uint64', name: 'destinationChainSelector', type: 'uint64' }],
    name: 'DestinationChainNotAllowed',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'bytes', name: 'result', type: 'bytes' }],
    name: 'ErrorInCall',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'uint256', name: 'value', type: 'uint256' },
    ],
    name: 'FailedToWithdrawEth',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'router', type: 'address' }],
    name: 'InvalidRouter',
    type: 'error',
  },
  { inputs: [], name: 'InvalidShortString', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'currentBalance', type: 'uint256' },
      { internalType: 'uint256', name: 'calculatedFees', type: 'uint256' },
    ],
    name: 'NotEnoughBalance',
    type: 'error',
  },
  { inputs: [], name: 'NothingToWithdraw', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'sender', type: 'address' }],
    name: 'SenderNotAllowed',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint64', name: 'sourceChainSelector', type: 'uint64' }],
    name: 'SourceChainNotAllowed',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'string', name: 'str', type: 'string' }],
    name: 'StringTooLong',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'userAddress', type: 'address' },
      { indexed: false, internalType: 'address', name: 'accountAddress', type: 'address' },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      { indexed: false, internalType: 'uint8', name: 'accountType', type: 'uint8' },
    ],
    name: 'AccountCreated',
    type: 'event',
  },
  { anonymous: false, inputs: [], name: 'EIP712DomainChanged', type: 'event' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'messageId', type: 'bytes32' },
      { indexed: true, internalType: 'uint64', name: 'sourceChainSelector', type: 'uint64' },
      { indexed: false, internalType: 'address', name: 'sender', type: 'address' },
      { indexed: false, internalType: 'bytes', name: 'text', type: 'bytes' },
      {
        components: [
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        indexed: false,
        internalType: 'struct Client.EVMTokenAmount[]',
        name: 'tokenAmounts',
        type: 'tuple[]',
      },
    ],
    name: 'MessageReceived',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'messageId', type: 'bytes32' },
      {
        components: [
          { internalType: 'uint64', name: 'destinationChainSelector', type: 'uint64' },
          { internalType: 'address', name: 'receiver', type: 'address' },
          { internalType: 'bytes', name: 'dataToSend', type: 'bytes' },
          { internalType: 'address', name: 'addressToExecute', type: 'address' },
          { internalType: 'uint256', name: 'valueToExecute', type: 'uint256' },
          { internalType: 'bytes', name: 'dataToExecute', type: 'bytes' },
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'address', name: 'feeToken', type: 'address' },
          { internalType: 'uint256', name: 'gasLimit', type: 'uint256' },
        ],
        indexed: false,
        internalType: 'struct ITransshipmentStructures.MassageParam',
        name: 'massageParam',
        type: 'tuple',
      },
      { indexed: false, internalType: 'uint256', name: 'fees', type: 'uint256' },
    ],
    name: 'MessageSent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
    ],
    name: 'OwnershipTransferRequested',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    inputs: [],
    name: 'NAME',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'VERSION',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'accountImplementation',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'accounts',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint64', name: '_destinationChainSelector', type: 'uint64' },
      { internalType: 'bool', name: 'allowed', type: 'bool' },
    ],
    name: 'allowlistDestinationChain',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_sender', type: 'address' },
      { internalType: 'bool', name: 'allowed', type: 'bool' },
    ],
    name: 'allowlistSender',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint64', name: '_sourceChainSelector', type: 'uint64' },
      { internalType: 'bool', name: 'allowed', type: 'bool' },
    ],
    name: 'allowlistSourceChain',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
    name: 'allowlistedDestinationChains',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'allowlistedSenders',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
    name: 'allowlistedSourceChains',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes', name: 'managerProof', type: 'bytes' },
      { internalType: 'address', name: 'feeToken', type: 'address' },
      { internalType: 'uint256', name: 'gasLimit', type: 'uint256' },
      { internalType: 'uint256', name: 'feeAmount', type: 'uint256' },
      {
        components: [
          { internalType: 'address', name: 'userAddress', type: 'address' },
          { internalType: 'uint256', name: 'userNonce', type: 'uint256' },
          { internalType: 'address', name: 'srcTokenAddress', type: 'address' },
          { internalType: 'uint256', name: 'srcTokenAmount', type: 'uint256' },
          { internalType: 'uint64', name: 'dstChainSelector', type: 'uint64' },
          { internalType: 'address', name: 'dstExecutor', type: 'address' },
          { internalType: 'address', name: 'dstTokenAddress', type: 'address' },
          { internalType: 'uint256', name: 'dstTokenAmount', type: 'uint256' },
          { internalType: 'address', name: 'dstReceiver', type: 'address' },
        ],
        internalType: 'struct ITransshipmentStructures.BridgeParams',
        name: 'params',
        type: 'tuple',
      },
    ],
    name: 'bridgeTokens',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'messageId', type: 'bytes32' },
          { internalType: 'uint64', name: 'sourceChainSelector', type: 'uint64' },
          { internalType: 'bytes', name: 'sender', type: 'bytes' },
          { internalType: 'bytes', name: 'data', type: 'bytes' },
          {
            components: [
              { internalType: 'address', name: 'token', type: 'address' },
              { internalType: 'uint256', name: 'amount', type: 'uint256' },
            ],
            internalType: 'struct Client.EVMTokenAmount[]',
            name: 'destTokenAmounts',
            type: 'tuple[]',
          },
        ],
        internalType: 'struct Client.Any2EVMMessage',
        name: 'message',
        type: 'tuple',
      },
    ],
    name: 'ccipReceive',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'uint8', name: 'accountType', type: 'uint8' },
    ],
    name: 'createAccount',
    outputs: [{ internalType: 'address', name: 'accountAddress', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'eip712Domain',
    outputs: [
      { internalType: 'bytes1', name: 'fields', type: 'bytes1' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'version', type: 'string' },
      { internalType: 'uint256', name: 'chainId', type: 'uint256' },
      { internalType: 'address', name: 'verifyingContract', type: 'address' },
      { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
      { internalType: 'uint256[]', name: 'extensions', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'userAddress', type: 'address' }],
    name: 'getAccountAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'userAddress', type: 'address' }],
    name: 'getCreatedAccountAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getLastReceivedMessageDetails',
    outputs: [
      { internalType: 'bytes32', name: 'messageId', type: 'bytes32' },
      { internalType: 'bytes', name: 'data', type: 'bytes' },
      { internalType: 'address', name: 'tokenAddress', type: 'address' },
      { internalType: 'uint256', name: 'tokenAmount', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRouter',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'manager',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'multicall',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 's_lastReceivedData',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 's_lastReceivedMessageId',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 's_lastReceivedTokenAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 's_lastReceivedTokenAmount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint64', name: 'destinationChainSelector', type: 'uint64' },
          { internalType: 'address', name: 'receiver', type: 'address' },
          { internalType: 'bytes', name: 'dataToSend', type: 'bytes' },
          { internalType: 'address', name: 'addressToExecute', type: 'address' },
          { internalType: 'uint256', name: 'valueToExecute', type: 'uint256' },
          { internalType: 'bytes', name: 'dataToExecute', type: 'bytes' },
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'address', name: 'feeToken', type: 'address' },
          { internalType: 'uint256', name: 'gasLimit', type: 'uint256' },
        ],
        internalType: 'struct ITransshipmentStructures.MassageParam',
        name: 'massageParam',
        type: 'tuple',
      },
    ],
    name: 'sendMassage',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint64', name: 'destinationChainSelector', type: 'uint64' },
          { internalType: 'address', name: 'receiver', type: 'address' },
          { internalType: 'bytes', name: 'dataToSend', type: 'bytes' },
          { internalType: 'address', name: 'addressToExecute', type: 'address' },
          { internalType: 'uint256', name: 'valueToExecute', type: 'uint256' },
          { internalType: 'bytes', name: 'dataToExecute', type: 'bytes' },
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'address', name: 'feeToken', type: 'address' },
          { internalType: 'uint256', name: 'gasLimit', type: 'uint256' },
        ],
        internalType: 'struct ITransshipmentStructures.MassageParam[]',
        name: 'massageParams',
        type: 'tuple[]',
      },
    ],
    name: 'sendUniversalMassage',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'to', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'userNonce',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_beneficiary', type: 'address' }],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_beneficiary', type: 'address' },
      { internalType: 'address', name: '_token', type: 'address' },
    ],
    name: 'withdrawToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
];
